### ISSUE TITLE
missing var

### ISSUE THREAD

**Issue by ibc** [nathanboktae/q-xhr#11]
https://github.com/nathanboktae/q-xhr/blob/master/q-xhr.js#L129

```js
mergeHeaders = function(config) {
```

=>

```js
var mergeHeaders = function(config) {
```

or

```js
function mergeHeaders(config) {
```

**Comment by nathanboktae** [comment]
No, it is one big [`var` declaration](https://github.com/nathanboktae/q-xhr/blob/b3ec0d1e7d356aa9eb03a9c0f231a480ce71bb6e/q-xhr.js#L124-L129) there that is all comma-delmited on multiple lines.

**Comment by ibc** [comment]
wow, sorry...

**Comment by nathanboktae** [comment]
yeah I should have indented the variables on multiple lines (I do that nowadays)

**Comment by ibc** [comment]
Welcome to the JS coding style war :)
