### ISSUE TITLE
Adding handler to xhr.upload causes Chrome and Firefox issue OPTIONS instead of POST when ports differ

### ISSUE THREAD

**Issue by youurayy** [nathanboktae/q-xhr#12]
Don't have much time to narrow this down, but basically, [after this change](https://github.com/nathanboktae/q-xhr/commit/15722978a60ed7c3af59760a68b0515118a142d0#diff-7e834aa9b184978d4a949015e524a6a6R305), making a `text/plain` `POST` request from `http://localhost:3000/` to `http://localhost:8080/url` makes the browser issue a pre-flight `OPTIONS` request, which is not issued when the above commit code is commented out.

Possibly a browser bug. Reality is that e.g. Zepto works, and q-xhr does not (or requires an additional request).

Ideally, an option would be added to q-xhr to prevent (or trigger) the addition of the `xhr.upload.onprogress` handler, which I believe is not needed in most of cases.

Screenshot of the OPTIONS request:
<img width="943" alt="screen shot 2015-11-16 at 2 50 22 am" src="https://cloud.githubusercontent.com/assets/588573/11172344/97f9464c-8c0e-11e5-879b-52d1d3fb2c4f.png">

Screenshot of the affecting code:
<img width="501" alt="screen shot 2015-11-16 at 3 04 31 am" src="https://cloud.githubusercontent.com/assets/588573/11172358/cabee41a-8c0e-11e5-9014-6187e0c80592.png">

I can make a PR if you prefer. Thanks.

**Comment by nathanboktae** [comment]
The same origin policy includes the port. This situation will always cause an OPTION request, regardless of the code creating the XHR. If you need to support cors, respond to the OPTIONS request, or use proxy middleware in your browser sync server.

**Comment by youurayy** [comment]
This situation IS NOT causing an OPTION request when the `xhr.upload` field is not accessed.

That's why it works in Zepto.

Would accepting my PR be a huge problem?

**Comment by youurayy** [comment]
Oh, I must add, that our test server is configured for CORS. So in that case.

**Comment by nathanboktae** [comment]
There is not tests or documentation for this PR. Can you explain to me how this works in Zepto? Basically if your claim is correct, Chrome and Firefox have a major security bug because they are allowing cors from one domain to another.

> I must add, that our test server is configured for CORS

Why is it returning 404 on an options request then?

**Comment by youurayy** [comment]
By the server being configured for CORS I mean that the server adds `Access-Control-Allow-Origin: *` to each response, as [spec'd here](http://enable-cors.org/server.html).

The reason why this works with Zepto, as I describe above, is that Zepto doesn't touch the `XmlHttpRequest.upload` field. Q-xhr touches it (adds a listener to `xhr.upload.onprogress`), because it allows for progress tracking during uploads.

However, for some unknown reason, possibly a browser (Chrome/Safari) bug, when a listener is added to `xhr.upload.onprogress`, the browser thinks it has to make a pre-flight OPTIONS request on POST, despite the server being configured for CORS.

And because I assume 99.9% of uses of Q-xhr don't need to upload (or track the upload progress), but at the same time to not break the existing behavior, I suggest to add an option which prevents the automatic addition of the listener to `xhr.upload.onprogress` by Q-xhr.

**Comment by nathanboktae** [comment]
That does seem weird. If you add this information to the README, documenting the option, 'll take the PR.

**Comment by youurayy** [comment]
Hi, sorry for the wait. The PR was updated with documentation. Thanks.

ps. The build fails because it cannot connect to Sauce Labs.

**Comment by nathanboktae** [comment]
Thanks!
