### ISSUE TITLE
NPM Package Out of Date

### ISSUE THREAD

**Issue by sandersky** [nathanboktae/q-xhr#5]
The current version is not in sync with the latest code and causes problems. It specifically needs the change https://github.com/nathanboktae/q-xhr/commit/adb061b707cb320ab7b06153031ea57441ba473f in order to work properly on Ubuntu. Can you release a new version to overcome this (I also noticed your package.json is set to 0.1.2 but your bower.json is set to 0.1.1 and the latest release on Github is 0.1.2).

**Comment by nathanboktae** [comment]
Thanks for the heads up - just published 0.1.2.
